---
driver:
  name: docker

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver_config:
      image: chef/ubuntu-14.04:11.16.2
      require_chef_omnibus: false

suites:
  - name: default
    run_list:
      - recipe[cm-update-server::default]
    attributes:
