---
driver:
  name: docker

driver_config:
  require_chef_omnibus: "11.18.12"

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[cm-update-server::default]
    attributes:
